---
- name: Configure AWS Transit VPC CSR to Connect to AWS VPC
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  
  vars:
    build_dir: "/tmp/"
    csr_aws_vpn_config:
      - vpn_id: 'A50'
        tunnel1_ip: '100'
        vgw_id: ' '
        acct_id: ' '
        cgw_id: ' '
        tunnel1_psk: ' '
        tunnel1_bgp: ' '
        tunnel2_bgp: ' '
        tunnel1_int_ip: ' '
        tunnel2_ip: '101'
        tunnel2_psk: ' '
        tunnel2_int_ip: ' '
        tunnel1_int_id: ' '
        tunnel2_int_id: ' '
        
  tasks:      
    - name: Build ISAKMP, IPSEC, BGP, VRF config to connect AWS VPC to AWS Transit CSR VPC
      template: src=template/csr-transit-aws-vpn.set.j2 dest={{build_dir}}/csr-transit-aws-vpn.set
      with_items: csr_az_vpn_config
